name: am_PlayerSize
author: TheNewManu
api: ["3.0.0APLHA7", "3.0.0-ALPHA8", "3.0.0-ALPHA9"]
main: emanuele0204\PlayerSize\PlayerSize

permissions:
 playersize:
  children:
   playersize.command:
    children:
     playersize.command.size:
      default: op
